version: 2

defaults: &defaults
    docker:
        - image: circleci/node:latest

filter-publish: &filter-publish
    filters:
        branches: { ignore: /.*/ }
        tags: {only: /^v\d*\.\d*\.\d*/}

workflows:
    version: 2
    go:
        jobs:
            - test
            - hold:
                requires: [ test ]
                type: approval
                <<: *filter-publish
            - derp:
                <<: *filter-publish
            - publish:
                requires: [ hold ]
                <<: *filter-publish

jobs:
    test:
        <<: *defaults
        steps:
            - run: pwd
            - checkout
            - restore-cache:
                key: node_modules
            - run: yarn
            - run: npm i bs-platform
            - save-cache:
                key: node_modules
                paths:
                    - node_modules
            - run: npm run build
            - persist_to_workspace:
                root: &root ~/project
                paths: .
            - run: yarn test
    publish:
        <<: *defaults
        steps:
            - attach_workspace:
                at: *root
            - run: "echo \"//registry.npmjs.org/:_authToken=$NPM_TOKEN\" > ~/.npmrc"
            - run: npm publish
    fail:
        <<: *defaults
        steps:
            - run: exit 1
    derp:
        <<: *defaults
        steps: [{run: echo derp}]
